version: '3.3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:  # TODO  content from .env files here
      - DOCKER=True
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=$PYTHONPATH:/code
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - SHELL=/bin/bash
    volumes:
      - ./:/code

# TODO any service present in tox comes here: Kafka, KeyDB (Redis), TempDB (Postgres)
